---
- name: Update webservers
  hosts: webservices
  become: true  
  
  tasks: 
   - name: Ensure apache is at the latest version
     ansible.builtin.apt:
      name: apache2
      state: latest
      update_cache: true